name: api_client
description: Client to access the api
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  ua_client_hints: ^1.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
