name: greenconnext_app
description: "GreenConnext Mobile Application"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DateTime
  intl: ^0.19.0

  # Google and Firebase
  firebase_core: ^2.32.0

  # Architecture
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  # UIs
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5
  greenconnext_ui:
    path: packages/greenconnext_ui

  # Domains
  api_client:
    path: packages/api_client
  authenticate_repository:
    path: packages/authenticate_repository
  announcement_repository:
    path: packages/announcement_repository
  calendar_event_repository:
    path: packages/calendar_event_repository


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_flavorizr: ^2.2.3

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
