name: greenconnext_app
description: "GreenConnext Mobile Application"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For DateTime
  intl: ^0.19.0

  # For Google and Firebase
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1

  # For Architecture
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # For Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # For Routing
  auto_route: ^9.2.2

  # For UIs
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5
  greenconnext_ui:
    path: packages/greenconnext_ui

  # For Domains
  api_client:
    path: packages/api_client
  authenticate_repository:
    path: packages/authenticate_repository
  announcement_repository:
    path: packages/announcement_repository
  calendar_event_repository:
    path: packages/calendar_event_repository
  user_credential_api:
    path: packages/user_credential_api


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
