name: authenticate_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.7.0
  google_sign_in: ^6.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  api_client:
    path: ../api_client

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
