name: authenticate_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  api_client:
    path: ../api_client

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
